### ISSUE TITLE
Toggle comment status

### ISSUE THREAD

**Issue by junkmechanic** [tpope/vim-commentary#75] opened 2016-07-21 02:03 UTC
Hi,

This is more of an issue when you want to change the status of multiple lines some of which are already commented out.
The current behavior is to comment out all the lines (this results in an extra layer of commentstring for the lines that were already commented out in the selection).
But quite often the need is to have the comment status inverted in the selection. That is to treat the selection as a combination of two groups, one that needs to be commented out and the other (which was already commented) to be un-commented.

There could be a different function for this, or my preference would be to have a flag that would decide between the current and this behavior.

Thanks!

**Comment by untergam** [comment] 2016-08-24 21:27
Hey,
Nice idea @junkmechanic , I also think such a feature would be great! In fact, I returned to the project repository today to see if such a feature already existed, and then found this request here. (I tried to implement such a mapping myself by reusing some of the plugin functions, but I miserably failed)

Just a quick C usecase example (would be very useful when doing debugging):

// int x = 0;
int x = 42;

to toggle both of these lines with the current shortcuts, I would do something like "gccjgcc". However, if for example gC (or any other prefix) would toggle each line of a motion individually, then the same could be achieved by just simply "gCj". Even more keystrokes could be saved if two entire code paragraphs need to be toggled.

I have no clue about vimscript etc, but my guess would be that @tpope could implement this in no time - and the commentary plugin would be even more awesome!!
 
Great work guys, Commentary is one of the most useful VIM Plugins for me!

**Comment by GandaG** [comment] 2016-11-04 15:23
Yup, this would be amazing!

**Comment by pylipp** [comment] 2017-12-10 10:53
I found a similar discussion at the `tcomment_vim` plugin issue page: https://github.com/tomtom/tcomment_vim/issues/139#issuecomment-88592516

Did not try to port it myself, maybe it helps you though.

**Comment by hwong557** [comment] 2019-01-02 02:31
Such a feature would be really helpful!

**Comment by wis** [comment] 2019-06-15 04:12
I use nerdcommenter now, here's [the relevant config](https://github.com/scrooloose/nerdcommenter/search?q=NERDSpaceDelims&unscoped_q=NERDSpaceDelims)
seems so good so far.

**Comment by minusf** [comment] 2019-10-16 12:10
indeed "toggle" is a white lie.  it seems it can toggle really only single lines. it does not toggle visual selections or multiple lines (python example):

```py
d=(
    # "test1",
    "test2",
)
```

Now i would like to toggle the commenting to be like this:

```py
d=(
    "test1",
    # "test2",
)
```

So i go into visual line mode and select both lines and press `gc`. the result is:

```py
d=(
    # # "test1",
    # "test2",
)
```

**Comment by minusf** [comment] 2019-10-16 12:20
> I use nerdcommenter now, here's the [command ](https://github.com/scrooloose/nerdcommenter/blob/25c2920fe8d6673886ddb80e969dacf66e606299/doc/NERD_commenter.txt#L105)

sigh.  nerdcommenter also has toggle (`<leader>c<space>`), that also doesnt "toggle". confusingly, it also has an "invert" command (`<leader>ci`) that actually toggles correctly.  so yes, that works.  (but for a change it ignores spaces: `'# text'` -> `' text'`).

**Comment by tpope** [comment] 2019-10-16 18:29
> indeed "toggle" is a white lie. it seems it can toggle really only single lines.

Wrong. It can toggle a million lines as long as they're all commented out first.

> sigh. nerdcommenter also has toggle (<leader>c<space>), that also doesnt "toggle"

Funny how every single commenting plugin has a definition of "toggle" that doesn't match yours, almost like the word doesn't mean what you insist it means!

**Comment by minusf** [comment] 2019-10-16 18:46
> > sigh. nerdcommenter also has toggle (c), that also doesnt "toggle"
> 
> Funny how every single commenting plugin has a definition of "toggle" that doesn't match yours, almost like the word doesn't mean what you insist it means!

now quick, without reading the docs, tell me what is the difference between "toggle comment" and "invert comment" :D

yeah, i admit it's a bit philosphical...  toggle does mean to switch between states, however the rest of the interpretation is up to the implementer.  a binary toggle for me means to apply `not` to every element of a selection.  the commenter plugins, as you point out very correctly, chose to interpret that as "toggle based on the topmost line".  totally fine.

but if i wanted to comment a whole block, i can use the comment command.
and if i wanted to uncomment a whole block, i can use the uncomment command.
but i cannot "toggle" every line of a selection, and that is why i think "toggle based on topmost line" is a duplicate of those 2 commands, while "inverting" (to use the nerdcommenter terminology) cannot be done in the other plugins at the moment.

it's frustrating for me, but perhaps heaven for the world.  i didnt mean to sound elitist, just frustrated :D

**Comment by tpope** [comment] 2019-10-16 20:53
If I have this code
```ruby
# Public API for creating a widget
def create_widget
    # for now, this is just a direct call to .new, but this will change in the future
    Widget.new
end
```

I can comment it out with `gcap`, and then uncomment it again with a second `gcap`. That's what I mean by "toggle". I think it's what any reasonable person would mean by "toggle", unless you added a qualifier like "toggle each line". If I said "toggle the lights", you'd turn them off if any were on, or turn them all on if they were all off. Nobody in their right mind would turn the off ones on and the on ones off.

If you want an invert behavior, you can create a map:

    `xnoremap <Leader>c :g/./Commentary<CR>`

The `:g/./` forces it to call `:Commentary` on every non-empty line, one by one.

I do not want to add additional standard maps at this time.

**Closed by tpope** 2019-10-16 20:53 UTC

**Comment by tpope** [comment] 2019-10-16 21:19
Let me add that it should be possible to replace the existing visual mode map this way, as long as you also create another map to `<Plug>Commentary`. This invert behavior mainly makes sense in visual mode I think so that seems like a good compromise.

**Comment by minusf** [comment] 2019-10-22 20:36
the `xnoremap` thingie works perfectly, thank you. as for replacing the current visual behaviour, that's your call.  i think it would be nice to stick an FAQ in the docs for this quick and dirty "invert" mapping and save some people a trip to the closed issues on github...

**Comment by jaja360** [comment] 2021-04-12 23:22
@minusf I agree. I had to do exactly that (read all closed issues) to find this !

I don't see the downside of this proposed visual multi-line toggle. It is what I would have naturally expected.

**Comment by tpope** [comment] 2021-04-13 23:11
Sometimes I want to comment out a chunk of code that has a comment inside of it.

**Comment by ernestchu** [comment] 2022-05-31 07:20
@minusf Can I see how you use it in your vim config? Thanks.
> the `xnoremap` thingie works perfectly, thank you.

**Comment by minusf** [comment] 2022-06-06 17:46
@ernestchu i used it as presented above.

```
xnoremap <Leader>c :g/./Commentary<CR>
```
