### ISSUE TITLE
How do you get it to work?

### ISSUE THREAD

**Issue by JohnSmall** [tpope/vim-commentary#46] opened 2015-05-25 07:16 UTC
I've installed commentary, read the help file, set a commentstring and I can use range:Commentary e.g. :7,14Commentary . So I think everything is set up, but typing gc or gcc on a line does nothing. 

Is there some special key sequence I have to use before 'gcc'

Incidentally, in the help file it says "Relies on 'commentstring' to be correctly set", but it doesn't say what 'correctly set' means. So I had to guess a few times and followed the example on the github page for apache. A example of what 'correctly set' means would be useful.

**Comment by tpope** [comment] 2015-05-25 18:29
If `:Commentary` is working then it's not a `'commentstring'` issue. Check `:nmap gc` and make sure you are typing it fast enough (under a second by default).

**Comment by JohnSmall** [comment] 2015-06-27 19:42
on :nmap gc I get

    n  gcu           <Plug>Commentary<Plug>Commentary
    n  gcc           <Plug>CommentaryLine
    n  gc            <Plug>Commentary

so it looks like it's all installed correctly. But it's just not working.

**Comment by rixx** [comment] 2015-10-14 15:45
I solved the very same problem by removing 

```
timeoutlen=100
```

from my `.vimrc`. (This is also included in [tpope/vim-sensible](https://github.com/tpope/vim-sensible) btw.)
I have absolutely no idea why this option would change the behaviour of  commentary, but it reproducably does. No other line in my config seems to have an impact.

**Comment by tpope** [comment] 2015-10-14 19:03
sensible.vim sets `'ttimeoutlen'` *not* `'timeoutlen'`. The former affects escape sequences while the latter affects all maps, making 100 ms indeed a ridiculous value to use.

**Comment by rixx** [comment] 2015-10-14 19:38
Oops. My bad.

**Comment by trisys3** [comment] 2016-06-06 15:09
Why is 100ms such a ridiculous value to use for `timeoutlen`? For example, `airline` recommends 50ms, which is half that value.

As an aside, [vim-surround](https://github.com/tpope/vim-surround), another one of @tpope's, also looks like it stops working with 100ms as the `timeoutlen`.

**Comment by rixx** [comment] 2016-06-06 15:25
@trisys3: As mentioned by @tpope, the value you are probably looking for ist `ttimeoutlen`, *not* `timeoutlen`. As you'll see, vim-airline also sets `ttimeoutlen`, not `timeoutlen`.

**Comment by trisys3** [comment] 2016-06-06 15:47
On `vim-airline`'s [FAQ](https://github.com/vim-airline/vim-airline/wiki/FAQ), the answer to the question "[There is a pause when leaving insert mode](https://github.com/vim-airline/vim-airline/wiki/FAQ#user-content-there-is-a-pause-when-leaving-insert-mode)" is "You need to set `timeoutlen` to a low number; 50 is recommended."

I do not know where they got this recommendation, as they do not cite any sources.

**Comment by trisys3** [comment] 2016-06-06 21:02
I found a question on vi.stackexchange.com that described my exact issue, down to the settings/plugins that were causing issues. The accepted answer suggests changing `ttimeoutlen` as well. Perhaps the `airline` FAQ just hasn't been updated yet?

**Comment by rixx** [comment] 2016-06-07 07:29
Seems that way - since it's a community wiki, you might as well just edit it in.

**Comment by trisys3** [comment] 2016-06-07 11:06
Wow, that was too easy. It wasn't even verified or anything. Thanks.

**Comment by trisys3** [comment] 2016-06-07 11:07
@JohnSmall, does this answer your question? Can we close it now?

**Comment by tpope** [comment] 2016-06-07 18:28
tbh I thought I closed it already.

**Closed by tpope** 2016-06-07 18:28 UTC
